/* Astranov Match Engine — business presets (supply ↔ demand parameters) */
window.AstranovMatchPresets = {
  /** Activatable demand fields per business — owners toggle via site config; Coders can extend */
  yacht_charter: {
    label: 'Yacht charter',
    mode: 'range',
    supply_kind: 'yacht',
    demand_fields: ['start_date', 'end_date', 'guests', 'cabins', 'budget', 'yacht_type', 'traits', 'crew_notes', 'crew_ack'],
    supply_fields: ['max_passengers', 'max_hire_days', 'price_per_day_eur', 'cabins', 'yacht_type', 'length_m', 'minimum_crew'],
    capacity_field: 'max_passengers',
    max_duration_field: 'max_hire_days',
    price_field: 'price_per_day_eur',
    resources: {
      enabled: true,
      label: 'Crew',
      required: { captain: 1, vice_captain: 1, cadet: 1 },
      default_rates: { captain: 300, vice_captain: 200, cadet: 100 },
    },
    legacy_tables: { catalog: 'yachting_yachts', availability: 'yachting_availability' },
  },
  diving_school: {
    label: 'Diving school',
    mode: 'slot',
    supply_kind: 'activity_slot',
    demand_fields: ['date', 'time', 'product', 'divers_count', 'passengers_count', 'certification'],
    supply_fields: ['capacity', 'prep_time_minutes', 'price'],
    capacity_field: 'capacity',
    price_field: 'price',
    resources: {
      enabled: true,
      label: 'Instructors',
      required: { instructor: 1 },
      default_rates: { instructor: 120 },
    },
  },
  restaurant: {
    label: 'Restaurant',
    mode: 'slot',
    supply_kind: 'table_slot',
    demand_fields: ['date', 'time', 'party_size', 'table_preference', 'dietary'],
    supply_fields: ['capacity', 'prep_time_minutes'],
    capacity_field: 'capacity',
    resources: { enabled: false },
  },
  hotel: {
    label: 'Hotel',
    mode: 'range',
    supply_kind: 'room',
    demand_fields: ['check_in', 'check_out', 'rooms', 'guests', 'room_type'],
    supply_fields: ['max_guests', 'price_per_night'],
    capacity_field: 'max_guests',
    price_field: 'price_per_night',
    resources: { enabled: false },
  },
  rental_car: {
    label: 'Rental car',
    mode: 'range',
    supply_kind: 'vehicle',
    demand_fields: ['pickup_date', 'return_date', 'vehicle_class', 'drivers'],
    supply_fields: ['seats', 'price_per_day'],
    capacity_field: 'seats',
    price_field: 'price_per_day',
    resources: { enabled: true, label: 'Delivery driver', required: { driver: 1 }, default_rates: { driver: 80 } },
  },
  generic: {
    label: 'Generic booking',
    mode: 'slot',
    supply_kind: 'service',
    demand_fields: ['date', 'start_date', 'end_date', 'quantity', 'notes'],
    supply_fields: ['capacity', 'price'],
    capacity_field: 'capacity',
    price_field: 'price',
    resources: { enabled: false },
  },
};